apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: lttborqou-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-2bb370ec56.t3a5.p3.openshiftapps.com/rhtap/rhtap-qe-go:0c5c53d3e787c4548febf363081894a35c63b633@sha256:feeffc71197d4681757efc66ae9dc54cc5287eab59b8a75237e9c26e68d0ef12
          name: container-image
